
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem test_domain)
    (:domain instance1)

    (:objects
        
    )

    (:init
        (= duration_extinguish_small_fire  1 )
        (= duration_evacuation  5 )
        (= duration_address_media  2 )
        (not_needed_diverted_traffic rural marketplace )
        (has_rescuers_number mesafire )
        (has_big_engines_number mesafire )
        (not_needed_active_local_alert policechief )
        (has_small_engines_number mesafire )
        (not_needed_attend_casualties byeng )
        (not_needed_diverted_traffic byeng rural )
        (not_needed_diverted_traffic rural byeng )
        (not_needed_diverted_traffic marketplace rural )
        (= duration_deploy_ladders  3 )
        (= duration_prepare_evacuation  1 )
        (not_needed_active_local_alert transportchief )
        (not_needed_diverted_traffic byeng marketplace )
        (has_rescuers_number adminfire )
        (= duration_deploy_rescuers  3 )
        (= duration_deploy_ambulances  2 )
        (has_police_car_number apachestation )
        (= duration_deploy_bulldozers  3 )
        (not_needed_search_casualties marketplace )
        (has_bulldozers_number adminfire )
        (has_ladders_number mesafire )
        (has_helicopters_number adminfire )
        (= duration_position_policemen  1 )
        (small_fire_at byeng )
        (not_needed_diverted_traffic marketplace byeng )
        (not_needed_attend_casualties marketplace )
        (= duration_deploy_police_cars  1 )
        (= total-cost  0 )
        (= duration_issue_local_alert  1 )
        (not_needed_active_local_alert firechief )
        (has_ambulances_number lukes )
        (not_needed_attend_casualties rural )
        (not_needed_search_casualties byeng )
        (not_needed_search_casualties rural )
        (not_needed_diverted_traffic rural rural )
        (has_small_engines_number adminfire )
        (fire_at byeng )
        (= duration_search_casualties  3 )
        (not_needed_address_media )
        (not_needed_diverted_traffic byeng byeng )
        (not_needed_diverted_traffic marketplace marketplace )
        (fire_at rural )
        (= duration_extinguish_big_fire  1 )
        (has_policemen_number courtstation )
        (= duration_attend_casualties  3 )
        (= duration_deploy_helicopters  3 )
        (= duration_contact_media  1 )
        (= duration_set_up_helpline  1 )
        (not_needed_active_local_alert medichief )
        (has_ladders_number adminfire )
        (= duration_deploy_big_engines  4 )
        (= duration_deploy_small_engines  2 )
        (= duration_barricade  1 )
        (has_police_car_number courtstation )
        (has_ambulances_number joseph )
        (has_bulldozers_number mesafire )
        (has_policemen_number apachestation )
        (= duration_unit_actions  1 )
        (= duration_block_road  2 )
        (has_helicopters_number mesafire )
    )

    (:goal
        (and (extinguished_fire rural ) (and (extinguished_fire byeng ) (and (not_needed_address_media ) (and (searched rural ) (addressed_media )))))
    )

    
    
    
)

