
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain instance1)
    (:requirements )
    (:types
        agents - object
        location - object
        police - object
        policestation - object
        pois - object
        fire - object
        firestation - object
        hospital - object
        transport - object
        medic - object
    )

    (:constants
        
    )

    (:predicates
        (= duration_extinguish_small_fire  1 )
        (= duration_evacuation  5 )
        (= duration_address_media  2 )
        (not_needed_diverted_traffic rural marketplace )
        (has_rescuers_number mesafire )
        (has_big_engines_number mesafire )
        (not_needed_active_local_alert policechief )
        (has_small_engines_number mesafire )
        (not_needed_attend_casualties byeng )
        (not_needed_diverted_traffic byeng rural )
        (not_needed_diverted_traffic rural byeng )
        (not_needed_diverted_traffic marketplace rural )
        (= duration_deploy_ladders  3 )
        (= duration_prepare_evacuation  1 )
        (not_needed_active_local_alert transportchief )
        (not_needed_diverted_traffic byeng marketplace )
        (has_rescuers_number adminfire )
        (= duration_deploy_rescuers  3 )
        (= duration_deploy_ambulances  2 )
        (has_police_car_number apachestation )
        (= duration_deploy_bulldozers  3 )
        (not_needed_search_casualties marketplace )
        (has_bulldozers_number adminfire )
        (has_ladders_number mesafire )
        (has_helicopters_number adminfire )
        (= duration_position_policemen  1 )
        (small_fire_at byeng )
        (not_needed_diverted_traffic marketplace byeng )
        (not_needed_attend_casualties marketplace )
        (= duration_deploy_police_cars  1 )
        (= total-cost  0 )
        (= duration_issue_local_alert  1 )
        (not_needed_active_local_alert firechief )
        (has_ambulances_number lukes )
        (not_needed_attend_casualties rural )
        (not_needed_search_casualties byeng )
        (not_needed_search_casualties rural )
        (not_needed_diverted_traffic rural rural )
        (has_small_engines_number adminfire )
        (fire_at byeng )
        (= duration_search_casualties  3 )
        (not_needed_address_media )
        (not_needed_diverted_traffic byeng byeng )
        (not_needed_diverted_traffic marketplace marketplace )
        (fire_at rural )
        (= duration_extinguish_big_fire  1 )
        (has_policemen_number courtstation )
        (= duration_attend_casualties  3 )
        (= duration_deploy_helicopters  3 )
        (= duration_contact_media  1 )
        (= duration_set_up_helpline  1 )
        (not_needed_active_local_alert medichief )
        (has_ladders_number adminfire )
        (= duration_deploy_big_engines  4 )
        (= duration_deploy_small_engines  2 )
        (= duration_barricade  1 )
        (has_police_car_number courtstation )
        (has_ambulances_number joseph )
        (has_bulldozers_number mesafire )
        (has_policemen_number apachestation )
        (= duration_unit_actions  1 )
        (= duration_block_road  2 )
        (has_helicopters_number mesafire )
        (extinguished_fire rural )
        (extinguished_fire byeng )
        (searched rural )
        (addressed_media )
        (alerted ?loc )
        (updated ?a )
        (has_police_car_number ?from )
        (alerted ?from )
        (deployed_police_cars ?to )
        (has_small_engines_number ?from )
        (needed_barricade ?to )
        (deployed_small_engines ?to )
        (deployed_engines ?to )
        (not_needed_barricade ?to )
        (has_big_engines_number ?from )
        (deployed_big_engines ?to )
        (has_ladders_number ?from )
        (deployed_ladders ?to )
        (has_bulldozers_number ?from )
        (deployed_bulldozers ?to )
        (has_helicopters_number ?from )
        (deployed_helicopters ?to )
        (has_rescuers_number ?from )
        (deployed_rescuers ?to )
        (has_ambulances_number ?from )
        (deployed_ambulances ?to )
        (has_policemen_number ?from )
        (positioned_policemen ?to )
        (media_contacted ?a )
        (active_helpline ?a )
        (not_needed_active_local_alert ?a )
        (active_local_alert ?a )
        (needed_active_local_alert ?a )
        (positioned_policemen ?from )
        (deployed_police_cars ?from )
        (blocked_road ?from ?to )
        (needed_diverted_traffic ?from ?to )
        (not_needed_diverted_traffic ?from ?to )
        (traffic_diverted ?from ?to )
        (prepared_evacuation ?from )
        (evacuated ?from ?to )
        (fire_at ?at )
        (small_fire_at ?at )
        (deployed_engines ?at )
        (extinguished_fire ?at )
        (needed_search_casualties ?at )
        (needed_address_media )
        (not_needed_search_casualties ?at )
        (deployed_big_engines ?at )
        (barricaded ?at )
        (not_needed_barricade ?at )
        (needed_barricade ?at )
        (deployed_helicopters ?at )
        (deployed_rescuers ?at )
        (deployed_bulldozers ?at )
        (needed_attend_casualties ?at )
        (searched ?at )
        (not_needed_attend_casualties ?at )
        (deployed_ambulances ?at )
        (attended_casualties ?at )
    )

    (:functions
        
    )

    

    
    (:action alert
     :parameters (?a - agents ?loc - location)
     :precondition (and )
     :effect (and
        (alerted ?loc ))
    )


    (:action update
     :parameters (?a - agents)
     :precondition (and )
     :effect (and
        (updated ?a ))
    )


    (:action deploy_police_cars
     :parameters (?a - police ?from - policestation ?to - pois)
     :precondition (and (has_police_car_number ?from ) (alerted ?from ))
     :effect (and
        (deployed_police_cars ?to )
        (not (has_police_car_number ?from ))
        (not (alerted ?from )))
    )


    (:action deploy_small_engines
     :parameters (?a - fire ?from - firestation ?to - pois)
     :precondition (and (has_small_engines_number ?from ) (alerted ?from ))
     :effect (and
        (needed_barricade ?to )
        (deployed_small_engines ?to )
        (deployed_engines ?to )
        (not (has_small_engines_number ?from ))
        (not (alerted ?from ))
        (not (not_needed_barricade ?to )))
    )


    (:action deploy_big_engines
     :parameters (?a - fire ?from - firestation ?to - pois)
     :precondition (and (has_big_engines_number ?from ) (alerted ?from ))
     :effect (and
        (deployed_big_engines ?to )
        (needed_barricade ?to )
        (deployed_engines ?to )
        (not (has_big_engines_number ?from ))
        (not (alerted ?from ))
        (not (not_needed_barricade ?to )))
    )


    (:action deploy_ladders
     :parameters (?a - fire ?from - firestation ?to - pois)
     :precondition (and (deployed_big_engines ?to ) (and (has_ladders_number ?from ) (alerted ?from )))
     :effect (and
        (deployed_ladders ?to )
        (not (has_ladders_number ?from ))
        (not (alerted ?from )))
    )


    (:action deploy_bulldozers
     :parameters (?a - fire ?from - firestation ?to - pois)
     :precondition (and (has_bulldozers_number ?from ) (alerted ?from ))
     :effect (and
        (deployed_bulldozers ?to )
        (not (has_bulldozers_number ?from ))
        (not (alerted ?from )))
    )


    (:action deploy_helicopters
     :parameters (?a - fire ?from - firestation ?to - pois)
     :precondition (and (has_helicopters_number ?from ) (alerted ?from ))
     :effect (and
        (deployed_helicopters ?to )
        (not (has_helicopters_number ?from ))
        (not (alerted ?from )))
    )


    (:action deploy_rescuers
     :parameters (?a - fire ?from - firestation ?to - pois)
     :precondition (and (has_rescuers_number ?from ) (alerted ?from ))
     :effect (and
        (deployed_rescuers ?to )
        (not (has_rescuers_number ?from ))
        (not (alerted ?from )))
    )


    (:action deploy_ambulances
     :parameters (?a - police ?from - hospital ?to - pois)
     :precondition (and (has_ambulances_number ?from ) (alerted ?from ))
     :effect (and
        (deployed_ambulances ?to )
        (not (has_ambulances_number ?from ))
        (not (alerted ?from )))
    )


    (:action position_policemen
     :parameters (?a - police ?from - policestation ?to - pois)
     :precondition (and (has_policemen_number ?from ) (alerted ?from ))
     :effect (and
        (positioned_policemen ?to )
        (not (alerted ?from )))
    )


    (:action contact_media
     :parameters (?a - agents)
     :precondition (and )
     :effect (and
        (media_contacted ?a ))
    )


    (:action set_up_helpline
     :parameters (?a - agents)
     :precondition (media_contacted ?a )
     :effect (and
        (active_helpline ?a ))
    )


    (:action issue_local_alert
     :parameters (?a - agents)
     :precondition (media_contacted ?a )
     :effect (and
        (not_needed_active_local_alert ?a )
        (active_local_alert ?a )
        (not (needed_active_local_alert ?a )))
    )


    (:action block_road
     :parameters (?a - transport ?from - location ?to - location)
     :precondition (and (deployed_police_cars ?to ) (and (positioned_policemen ?to ) (and (positioned_policemen ?from ) (and (deployed_police_cars ?from ) (active_local_alert ?a )))))
     :effect (and
        (blocked_road ?from ?to )
        (needed_diverted_traffic ?from ?to )
        (needed_active_local_alert ?a )
        (not (not_needed_diverted_traffic ?from ?to ))
        (not (not_needed_active_local_alert ?a )))
    )


    (:action divert_traffic
     :parameters (?a - transport ?from - location ?to - location)
     :precondition (and (blocked_road ?from ?to ) (active_local_alert ?a ))
     :effect (and
        (not_needed_diverted_traffic ?from ?to )
        (traffic_diverted ?from ?to )
        (not (needed_diverted_traffic ?from ?to )))
    )


    (:action prepare_evacuation
     :parameters (?a - police ?from - location)
     :precondition (active_local_alert ?a )
     :effect (and
        (prepared_evacuation ?from ))
    )


    (:action evacuate
     :parameters (?a - police ?from - location ?to - location)
     :precondition (and (positioned_policemen ?from ) (and (prepared_evacuation ?from ) (and (blocked_road ?from ?to ) (deployed_police_cars ?from ))))
     :effect (and
        (evacuated ?from ?to ))
    )


    (:action extinguish_small_fire
     :parameters (?a - fire ?at - pois)
     :precondition (and (fire_at ?at ) (and (small_fire_at ?at ) (deployed_engines ?at )))
     :effect (and
        (extinguished_fire ?at )
        (needed_search_casualties ?at )
        (needed_address_media )
        (not (fire_at ?at ))
        (not (small_fire_at ?at ))
        (not (not_needed_search_casualties ?at ))
        (not (not_needed_address_media )))
    )


    (:action extinguish_big_fire
     :parameters (?a - fire ?at - pois)
     :precondition (and (fire_at ?at ) (deployed_big_engines ?at ))
     :effect (and
        (extinguished_fire ?at )
        (needed_search_casualties ?at )
        (not (fire_at ?at ))
        (not (not_needed_search_casualties ?at )))
    )


    (:action barricade
     :parameters (?a - fire ?at - pois)
     :precondition (deployed_engines ?at )
     :effect (and
        (needed_active_local_alert ?a )
        (barricaded ?at )
        (not_needed_barricade ?at )
        (not (not_needed_active_local_alert ?a ))
        (not (needed_barricade ?at )))
    )


    (:action search_casualties
     :parameters (?a - fire ?at - pois)
     :precondition (and (deployed_helicopters ?at ) (and (extinguished_fire ?at ) (and (deployed_rescuers ?at ) (deployed_bulldozers ?at ))))
     :effect (and
        (needed_attend_casualties ?at )
        (needed_address_media )
        (searched ?at )
        (not (not_needed_attend_casualties ?at ))
        (not (not_needed_address_media )))
    )


    (:action attend_casualties
     :parameters (?a - medic ?at - pois)
     :precondition (and (needed_attend_casualties ?at ) (deployed_ambulances ?at ))
     :effect (and
        (needed_address_media )
        (not_needed_attend_casualties ?at )
        (attended_casualties ?at )
        (not (needed_attend_casualties ?at ))
        (not (not_needed_address_media )))
    )


    (:action address_media
     :parameters (?a - agents)
     :precondition (and (needed_address_media ) (media_contacted ?a ))
     :effect (and
        (not_needed_address_media )
        (addressed_media )
        (not (needed_address_media )))
    )

)